title: Austin American-Statesman nerd blog
email: interactives@statesman.com
description:
  The Austin American-Statesman's nerrrrrrrrd blog.
baseurl: ""
url: "http://statesman.github.io"
twitter_username: aasinteractive
github_username:  statesman
email: interactives@statesman.com

markdown: kramdown

# alias data directory so it gets built out
data_dir: data

# don't build these files/dirs out
exclude: [README.md, package.json, gruntfile.js, node_modules]