title: Your awesome title
email: interactives@statesman.com
description:
  The Austin American-Statesman's nerrrrrrrrd blog.
baseurl: "/blog"
url: "http://statesman.github.io"
twitter_username: aasinteractive
github_username:  statesman

markdown: kramdown

# aliasing 'at data dir so it gets built out
data_dir: data
